application: vgmdbapi
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  GAE_BASEURL: https://vgmdbapi.appspot.com/

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: wsgi.application

libraries:
- name: markupsafe
  version: latest
- name: lxml
  version: latest
- name: yaml
  version: latest
- name: setuptools
  version: latest

